// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: file.proto

package file

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on FileRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FileRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FileRequestMultiError, or
// nil if none found.
func (m *FileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_FileRequest_Id_Pattern.MatchString(m.GetId()) {
		err := FileRequestValidationError{
			field:  "Id",
			reason: "value does not match regex pattern \"^[a-zA-Z0-9]{32}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return FileRequestMultiError(errors)
	}

	return nil
}

// FileRequestMultiError is an error wrapping multiple validation errors
// returned by FileRequest.ValidateAll() if the designated constraints aren't met.
type FileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileRequestMultiError) AllErrors() []error { return m }

// FileRequestValidationError is the validation error returned by
// FileRequest.Validate if the designated constraints aren't met.
type FileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileRequestValidationError) ErrorName() string { return "FileRequestValidationError" }

// Error satisfies the builtin error interface
func (e FileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileRequestValidationError{}

var _FileRequest_Id_Pattern = regexp.MustCompile("^[a-zA-Z0-9]{32}$")
