// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: price.proto

package price

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PriceRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PriceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PriceRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PriceRequestMultiError, or
// nil if none found.
func (m *PriceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PriceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _PriceRequest_Metal_InLookup[m.GetMetal()]; !ok {
		err := PriceRequestValidationError{
			field:  "Metal",
			reason: "value must be in list [au ag]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PriceRequestMultiError(errors)
	}

	return nil
}

// PriceRequestMultiError is an error wrapping multiple validation errors
// returned by PriceRequest.ValidateAll() if the designated constraints aren't met.
type PriceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PriceRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PriceRequestMultiError) AllErrors() []error { return m }

// PriceRequestValidationError is the validation error returned by
// PriceRequest.Validate if the designated constraints aren't met.
type PriceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PriceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PriceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PriceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PriceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PriceRequestValidationError) ErrorName() string { return "PriceRequestValidationError" }

// Error satisfies the builtin error interface
func (e PriceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPriceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PriceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PriceRequestValidationError{}

var _PriceRequest_Metal_InLookup = map[string]struct{}{
	"au": {},
	"ag": {},
}

// Validate checks the field values on PriceResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PriceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PriceResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PriceResponseMultiError, or
// nil if none found.
func (m *PriceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PriceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Price

	if len(errors) > 0 {
		return PriceResponseMultiError(errors)
	}

	return nil
}

// PriceResponseMultiError is an error wrapping multiple validation errors
// returned by PriceResponse.ValidateAll() if the designated constraints
// aren't met.
type PriceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PriceResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PriceResponseMultiError) AllErrors() []error { return m }

// PriceResponseValidationError is the validation error returned by
// PriceResponse.Validate if the designated constraints aren't met.
type PriceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PriceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PriceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PriceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PriceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PriceResponseValidationError) ErrorName() string { return "PriceResponseValidationError" }

// Error satisfies the builtin error interface
func (e PriceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPriceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PriceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PriceResponseValidationError{}
