// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: storage.proto

package storage

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on StateRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StateRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StateRequestMultiError, or
// nil if none found.
func (m *StateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BotId

	if len(errors) > 0 {
		return StateRequestMultiError(errors)
	}

	return nil
}

// StateRequestMultiError is an error wrapping multiple validation errors
// returned by StateRequest.ValidateAll() if the designated constraints aren't met.
type StateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StateRequestMultiError) AllErrors() []error { return m }

// StateRequestValidationError is the validation error returned by
// StateRequest.Validate if the designated constraints aren't met.
type StateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StateRequestValidationError) ErrorName() string { return "StateRequestValidationError" }

// Error satisfies the builtin error interface
func (e StateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StateRequestValidationError{}

// Validate checks the field values on StateResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StateResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StateResponseMultiError, or
// nil if none found.
func (m *StateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *StateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetOccupiedCells()))
		i := 0
		for key := range m.GetOccupiedCells() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetOccupiedCells()[key]
			_ = val

			// no validation rules for OccupiedCells[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, StateResponseValidationError{
							field:  fmt.Sprintf("OccupiedCells[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, StateResponseValidationError{
							field:  fmt.Sprintf("OccupiedCells[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return StateResponseValidationError{
						field:  fmt.Sprintf("OccupiedCells[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	// no validation rules for Total

	// no validation rules for Available

	if len(errors) > 0 {
		return StateResponseMultiError(errors)
	}

	return nil
}

// StateResponseMultiError is an error wrapping multiple validation errors
// returned by StateResponse.ValidateAll() if the designated constraints
// aren't met.
type StateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StateResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StateResponseMultiError) AllErrors() []error { return m }

// StateResponseValidationError is the validation error returned by
// StateResponse.Validate if the designated constraints aren't met.
type StateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StateResponseValidationError) ErrorName() string { return "StateResponseValidationError" }

// Error satisfies the builtin error interface
func (e StateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StateResponseValidationError{}

// Validate checks the field values on OccupiedCell with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OccupiedCell) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OccupiedCell with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OccupiedCellMultiError, or
// nil if none found.
func (m *OccupiedCell) ValidateAll() error {
	return m.validate(true)
}

func (m *OccupiedCell) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Domain

	// no validation rules for Transaction

	if len(errors) > 0 {
		return OccupiedCellMultiError(errors)
	}

	return nil
}

// OccupiedCellMultiError is an error wrapping multiple validation errors
// returned by OccupiedCell.ValidateAll() if the designated constraints aren't met.
type OccupiedCellMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OccupiedCellMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OccupiedCellMultiError) AllErrors() []error { return m }

// OccupiedCellValidationError is the validation error returned by
// OccupiedCell.Validate if the designated constraints aren't met.
type OccupiedCellValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OccupiedCellValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OccupiedCellValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OccupiedCellValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OccupiedCellValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OccupiedCellValidationError) ErrorName() string { return "OccupiedCellValidationError" }

// Error satisfies the builtin error interface
func (e OccupiedCellValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOccupiedCell.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OccupiedCellValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OccupiedCellValidationError{}
